version: '3.7'

services:
  react_dev:
    container_name: rd_dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/home/app:rw'
      - './home/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
